pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('starter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('starter') {
                    sh 'mvn -B clean package'
                }
            }
            post {
                always {
                    junit testResults: '**/target/surefire-reports/*.xml, **/target/failsafe-reports/*.xml', allowEmptyResults: false                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'starter/target/*.jar', fingerprint: true
            }
        }
    }
}
